#!/bin/bash

# get workspace numbers
WS_STRING=$(i3-msg -t get_workspaces   | jq '.[] | (.num)')
WS_ARRAY=()

# put workspace numbers into array
for ws in $WS_STRING; do WS_ARRAY+=($ws); done

# list of all possible workspaces (change if you have more)
ALL_WS=({1..10})


# return 0 if element in array, 1 otherwise
containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}


# check for move container flag
focContainer=false
while getopts 'm' opt; do
    case $opt in
        m) focContainer=true ;;
        *) echo 'Error in command line parsing' >&2
            exit 1
    esac
done

# loop through all workspaces and find first that isn't in use
for ws in ${ALL_WS[@]}
do 
    if  ! containsElement $ws "${WS_ARRAY[@]}"
    then
        if "$focContainer"
        then
            # if -m flag is passed, focus new workspace
            i3-msg move container to workspace $ws;
#    I added this, instead of using wmctrl to set a hint, just focus the new workspace bruv.
	    i3-msg [workspace="$ws"] focus 

        else
            # otherwise, move without focusing
            i3-msg move container to workspace $ws;
        fi
        break
    fi
done
